site_name: SciKeras documentation

theme:
  name: material

nav:
  - Introduction: README.md
  - Quickstart: quickstart.md
  - Wrapper API Overview: wrappers.md
  - API Details: api.md
  - Contributing: contributing.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - pymdownx.superfences
  - toc:
      permalink: 
